In [1]:
print('Hi!')
import numpy as np
import pandas as pd
print(pd.__version__)

data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

Hi!
2.3.3


0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1]

np.float64(0.5)

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data['b']

np.float64(0.5)

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [10]:
data[5]

np.float64(0.5)

In [11]:
population_dict = {'California': 35332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    35332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [12]:
population['California']

np.int64(35332521)

In [13]:
population['California':'New York']

California    35332521
Texas         26448193
New York      19651127
dtype: int64

In [14]:
# pd.Series(data, index=index)

pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [15]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [16]:
pd.Series({2: 'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [17]:
pd.Series({2: 'a', 1:'b', 3:'c'}, index=[2, 3])

2    a
3    c
dtype: object

In [18]:
aria_dict =  {'California': 423967,
              'Texas': 695662,
              'New York': 141297,
              'Florida': 170312,
              'Illinois': 149995}
area = pd.Series(aria_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [19]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    35332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [20]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [21]:
states.columns

Index(['population', 'area'], dtype='object')

Object DataFrame as special dictionary

In [22]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Create DataFrame objects

From one object Series

In [23]:
pd.DataFrame(population, columns=['population'])

population
California    35332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

From a list of dictionary

In [24]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [25]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

NaN - Not a number

From a dictionary of Series objects

In [26]:
pd.DataFrame({'population': population, 'area': area})

population    area
California    35332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

From a two-dimensional NumPy array

In [27]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.580176  0.855174
b  0.551384  0.856431
c  0.807215  0.078055

The Index object from the Pandas library

In [28]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

Index object as an immutable array

In [29]:
print(ind[1])
print(ind[::2])
print(ind.size, ind.shape, ind.ndim, ind.dtype)

3
Index([2, 5, 11], dtype='int64')
5 (5,) 1 int64


In [30]:
# ind[1] = 0

Index as an ordered set

In [31]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [32]:
indA.intersection(indB) # intesection

Index([3, 5, 7], dtype='int64')

In [33]:
indA.union(indB) # union

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [34]:
indA.symmetric_difference(indB) # symmetric difference

Index([1, 2, 9, 11], dtype='int64')

INDEXING AND DATA SELECTION

*** Retrieving data from a Series object ***

Series object as a dictionary

In [35]:
# import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [36]:
data['b']

np.float64(0.5)

In [37]:
'a' in data

True

In [38]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [39]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [40]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

Series object as one-dimentional array

In [42]:
# slice by means of an explicit index
data['a': 'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [43]:
# slice by means of an implicite integer index
data[0: 2]

a    0.25
b    0.50
dtype: float64

In [44]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [45]:
# "fancy" indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

Indexers: loc, iloc and ix

In [47]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [48]:
# using an explicite index under indexing
data[1]

'a'

In [49]:
# using an implicite index under a slice
data[1: 3]

3    b
5    c
dtype: object

In [50]:
data.loc[1]

'a'

In [51]:
data.loc[1: 3]

1    a
3    b
dtype: object

In [52]:
data.iloc[1]

'b'

In [2]:
data.iloc[1: 3]

1    0.50
2    0.75
dtype: float64

*** Retrieving Data from a DataFrame object ***

DataFrame object as a dictionary

In [4]:
area = pd.Series({'California': 423967,
                  'Texas': 695662,
                  'New York': 141297,
                  'Florida': 170312,
                  'Illinois': 149995})

pop =  pd.Series({'California': 35332521,
                  'Texas': 26448193,
                  'New York': 19651127,
                  'Florida': 19552860,
                  'Illinois': 12882135})

data = pd.DataFrame({'area': area, 'pop': pop})
data

area       pop
California  423967  35332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [5]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [6]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [7]:
data.area is data['area']

True

In [8]:
data.pop is data['pop']

False

In [10]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  35332521   83.337904
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

DataFrame object as a two-dimentional array

In [11]:
data.values

array([[4.23967000e+05, 3.53325210e+07, 8.33379037e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [12]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.533252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  8.333790e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [13]:
data.values[0]

array([4.23967000e+05, 3.53325210e+07, 8.33379037e+01])

In [14]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [15]:
data.iloc[:3, :2]

area       pop
California  423967  35332521
Texas       695662  26448193
New York    141297  19651127

In [18]:
data.loc[:'New York', :'pop']

area       pop
California  423967  35332521
Texas       695662  26448193
New York    141297  19651127

In [21]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [22]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  35332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

Additional sintax for indexing

In [23]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [24]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [25]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121